on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
          npm run export

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.tshaworx.co.za
          username: weatherapp@weatherapp.tshaworx.co.za
          password: ${{ secrets.Afrihost }}
          local-dir: ./out/
